version: '3.9'

services:
  benchmark_node_250mhz_500mb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_250mhz_500mb
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500MB'
    volumes:
      - ./test_results/node_250mhz_500mb:/test_results
    environment:
      - RUNTIME=node
      - CPU_LIMIT=250MHz
      - MEM_LIMIT=500MB

  benchmark_deno_250mhz_500mb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_250mhz_500mb
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500MB'
    volumes:
      - ./test_results/deno_250mhz_500mb:/test_results
    environment:
      - RUNTIME=deno
      - CPU_LIMIT=250MHz
      - MEM_LIMIT=500MB

  benchmark_bun_250mhz_500mb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_250mhz_500mb
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '500MB'
    volumes:
      - ./test_results/bun_250mhz_500mb:/test_results
    environment:
      - RUNTIME=bun
      - CPU_LIMIT=250MHz
      - MEM_LIMIT=500MB

  benchmark_node_500mhz_500mb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_500mhz_500mb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500MB'
    volumes:
      - ./test_results/node_500mhz_500mb:/test_results
    environment:
      - RUNTIME=node
      - CPU_LIMIT=500MHz
      - MEM_LIMIT=500MB

  benchmark_deno_500mhz_500mb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_500mhz_500mb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500MB'
    volumes:
      - ./test_results/deno_500mhz_500mb:/test_results
    environment:
      - RUNTIME=deno
      - CPU_LIMIT=500MHz
      - MEM_LIMIT=500MB

  benchmark_bun_500mhz_500mb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_500mhz_500mb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '500MB'
    volumes:
      - ./test_results/bun_500mhz_500mb:/test_results
    environment:
      - RUNTIME=bun
      - CPU_LIMIT=500MHz
      - MEM_LIMIT=500MB

  benchmark_node_1ghz_1gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_1ghz_1gb
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1GB'
    volumes:
      - ./test_results/node_1ghz_1gb:/test_results
    environment:
      - RUNTIME=node
      - CPU_LIMIT=1GHz
      - MEM_LIMIT=1GB

  benchmark_deno_1ghz_1gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_1ghz_1gb
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1GB'
    volumes:
      - ./test_results/deno_1ghz_1gb:/test_results
    environment:
      - RUNTIME=deno
      - CPU_LIMIT=1GHz
      - MEM_LIMIT=1GB

  benchmark_bun_1ghz_1gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_1ghz_1gb
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1GB'
    volumes:
      - ./test_results/bun_1ghz_1gb:/test_results
    environment:
      - RUNTIME=bun
      - CPU_LIMIT=1GHz
      - MEM_LIMIT=1GB

  benchmark_node_2ghz_2gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_2ghz_2gb
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2GB'
    volumes:
      - ./test_results/node_2ghz_2gb:/test_results
    environment:
      - RUNTIME=node
      - CPU_LIMIT=2GHz
      - MEM_LIMIT=2GB

  benchmark_deno_2ghz_2gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_2ghz_2gb
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2GB'
    volumes:
      - ./test_results/deno_2ghz_2gb:/test_results
    environment:
      - RUNTIME=deno
      - CPU_LIMIT=2GHz
      - MEM_LIMIT=2GB

  benchmark_bun_2ghz_2gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_2ghz_2gb
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2GB'
    volumes:
      - ./test_results/bun_2ghz_2gb:/test_results
    environment:
      - RUNTIME=bun
      - CPU_LIMIT=2GHz
      - MEM_LIMIT=2GB

  benchmark_node_2ghz_5gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_2ghz_5gb
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '5GB'
    volumes:
      - ./test_results/node_2ghz_5gb:/test_results
    environment:
      - RUNTIME=node
      - CPU_LIMIT=2GHz
      - MEM_LIMIT=5GB

  benchmark_deno_2ghz_5gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_2ghz_5gb
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '5GB'
    volumes:
      - ./test_results/deno_2ghz_5gb:/test_results
    environment:
      - RUNTIME=deno
      - CPU_LIMIT=2GHz
      - MEM_LIMIT=5GB

  benchmark_bun_2ghz_5gb:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: benchmark_2ghz_5gb
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '5GB'
    volumes:
      - ./test_results/bun_2ghz_5gb:/test_results
    environment:
      - RUNTIME=bun
      - CPU_LIMIT=2GHz
      - MEM_LIMIT=5GB